<?php
if (!isset($docs)) {
    $docs = [];
}
if (!isset($opendocs)) {
    $opendocs = [];
}
if (!isset($users)) {
    $users = [];
}

?>
<div class="contain">
    <form method="post" action="share">
        <div>&nbsp;</div>
        <p>
            <i class="fa fa-info-circle text-info">&nbsp;Vous &ecirc;tes sur le point de partager un document. Ce document est un dossier, il sera partager avec tous les sous dossier ou fichier qu'il contient. </i>
        </p>
        <br>
        <div class="row-fluid">

            <div class="col-md-12 row notification">
                <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
                    <div><p><?php $this->flashSession->output() ?></p></div>
                <?php endif; ?>
            </div>

            <div class="col-md-8"><a href="#"><span class="fa fa-long-arrow-right" data-toggle="collapse" data-target="#alldoc">&nbsp; <i class="fa fa-folder text-warning">&nbsp; <?= $docs->nomdos ?></i></span></a></div>
            <div class="col-md-4">
                <button class="btn btn-default btn-sm fa fa-send" type="submit">&nbsp; Envoyer</button>
            </div>

            <div id="alldoc" class="collapse col-md-8">
                <div class="col-md-offset-1 col-md-11"> 
                    <table class="table table-responsive">
                        <?php foreach ($opendocs as $value): ?>
                            <tr>
                                <td><span class="fa fa-folder text-warning"></span></td>
                                <td><?= $value->nomdos ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
                <div class="col-md-offset-2 col-md-10"> 
                    <table class="table table-responsive">
                        <?php foreach ($openfile as $value): ?>
                            <tr>
                                <td><span class="fa fa-file text-info"></span></td>
                                <td><?= $value->description ?></td>
                                <td><?= $value->nomfile ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </table>
                </div>
            </div>
        </div>
        <div class="clearfix">&nbsp;</div>
        <div class="row-fluid">
            <div class="col-md-6">
                <textarea class="form-control" placeholder="Message" name="message" rows="3" cols="10" required=""></textarea>
                <input type="hidden" name="idShare" value="<?= $docs->iddos ?>">
                <input type="hidden" name="typeShare" value="doc">
            </div>
        </div>
        <div class="clearfix">&nbsp;</div>
        <div class="clearfix">&nbsp;</div>
        <p>
            <i class="text-info">&nbsp; Veuillez selectionner les utilisateurs auquel vous d&eacute;sirez envoyer ce document. </i>
        </p>
        <div class="row-fluid">
            <div class="col-md-12"> 
                <table class="table table-responsive table-striped table-hover ui-datatable" 
                       data-global-search="false"
                       data-length-change="true"
                       data-info="true"
                       data-paging="true"
                       data-page-length="10">
                    <thead class="table-responsive">
                        <tr class="table-striped">
                            <th></th>
                            <th></th>
                            <th data-filterable="text" data-sortable="true"></th>
                            <th align='center'></th>
                        </tr>
                    </thead>
                    <tbody class="table-responsive">
                        <?php foreach ($users as $user): ?>
                            <tr>
                                <td><input type="checkbox" class="checkbox-primary" name="users[]" value="<?= $user->iduser; ?>"></td>
                                <td><span class="fa fa-user text-info"></span></td>
                                <td><?= $user->fulname ?></td>
                                <td><?= $user->email ?></td>
                            </tr>
                        <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

    </form>
</div>

