<?php
if (!isset($folder)) {
    $folder = [];
}

?>
<div class="contain">
    <h4 class="text-warning">Dossiers re&ccedil;u</h4>
    <div class="clearfix">&nbsp;</div>
    <div class="col-md-12 row notification">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
        <?php endif; ?>
    </div>
    <div class="clearfix">&nbsp;</div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-responsive table-striped table-bordered table-hover">
                <thead class="table-responsive">
                    <tr class="table-striped">
                        
                        <th>&nbsp;</th>
                        <th><b>Nom dossier</b></th>
                        <th><b>file(s)</b></th>
                        <th align='center'><b>ouvrir</b></th>                      
                    </tr>
                </thead>
                <tbody class="table-responsive">                  
                        <tr class="table-striped">
                            <td><b> &nbsp;<i class="fa fa-folder-open text-warning"></i></b></td>
                            <td ><?= $folder->nomdos ?></td>
                            <td><?= "(" . count($folder->fichier) . ")" ?></td>
                            <td align="center"><a href="open?id=<?= base64_encode($folder->iddos) ?>"><span class="glyphicon glyphicon-eye-open text-primary"></span></a></td>                    
                        </tr>                 
                </tbody>
            </table>
        </div>
    </div>
</div>


