<?php
if (!isset($docFile)) {
    $docFile = [];
}

$iduser= $this->session->get('userid');

$permission = explode(",", $docFile->permission); 
?>
<div class="contain">
    <h4 class="text-warning">Modification de fichier</h4>
    <div class="clearfix">&nbsp;</div>
    <form method="post" action="updateFile?id=<?= base64_encode($docFile->idfile).'.'.base64_encode($docFile->iddos) ?>" enctype="multipart/form-data">
        <div class="row">
          
            <div class="col-md-12">
                <span class="clearfix">&nbsp;</span>
                <div class="col-md-12">
                    <table class="table table-responsive">
                        <tr>
                            <td colspan="4">
                                <span class="col-md-5"><input type="text" name="descfile" value="<?= $docFile->description ?>" class="form-control" placeholder="description fichier" required=""></span>
                                <span class="col-md-4"><input type="file" name="fichier[]"></span>
                                <span class="col-md-2" id="bloc-button">
                                    <a href="#" class="btn btn-default btn-xs" >
                                        <i class="fa fa-file text-info"></i> &nbsp;<?= $docFile->nomfile ?>
                                    </a>
                                </span><br>
                            </td>
                        </tr>                               
                    </table> 
                    <table class="table table-responsive"id="tableau_doc" >
                        <tr>
                            <td colspan="4">
                            </td>
                        </tr>
                    </table>

                </div>
                <div class="row">
                    <span class="col-md-8">
                        <?php if($docFile->iduser == $iduser): ?>
                        <div class="clearfix">&nbsp;</div>
                        <div class="col-md-12">
                            <h4 class="text-warning">modifier les droits d&apos;acc&egrave;s</h4>
                            <table class="table table-responsive">
                                <tr class="table-striped">
                                    <td><label class="checkbox-inline"><input type='checkbox'  name='config[]' value="read" <?= (in_array("read", $permission)) ? "checked='checked' " : "" ?>> droit de lecture du fichier</label></td>
                                </tr>
                                <tr class="table-striped">
                                    <td><label class="checkbox-inline"><input type='checkbox'  name='config[]' value="readWrite" <?= (in_array("readWrite", $permission)) ? "checked='checked' " : "" ?>>droit de lecture et &eacute;criture du fichier</label></td>
                                </tr>
                            </table> 
                            <div class="clearfix">&nbsp;</div>
                     
                        </div>
                        <?php endif;?>
                    </span>
                    <span class="col-md-4">
                        <a href="openFolder?id=<?= base64_encode($docFile->iddos) ?>" class="btn btn-default btn-sm"><i class="fa fa-backward text-warning"></i>&nbsp; Retour &agrave; la liste</a>
                        <button class="btn btn-primary fa fa-check " type="submit" >&nbsp;Modifier</button>
                    </span>
                </div>
            </div>
        </div>
    </form>
    <div class="clearfix">&nbsp;</div>
    <div class="col-md-12 row notification">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
        <?php endif; ?>
    </div>
    <div class="clearfix">&nbsp;</div>
   
</div>

