<?php
if (!isset($contacts)) {
    $contacts = [];
}
?>
<div class="contain">
    <div class="clearfix">&nbsp;</div>
    <h4 class="text-warning">Mes contacts </h4> <h5>/ <a href='newContact'>Nouveau contact</a></h5>

    <div class="clearfix">&nbsp;</div>
    <div class="col-md-12 row notification">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
        <?php endif; ?>
    </div>
    <div class="clearfix">&nbsp;</div>
    <div class="row">
        <div class="col-md-12">
             <table class="table table-responsive table-striped table-hover ui-datatable" 
                    data-global-search="false"
                    data-length-change="true"
                    data-info="true"
                    data-paging="true"
                    data-page-length="10"
                    >
                <thead class="table-responsive">
                <tr class="table-striped">
                    <th data-filterable="text" >&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                    <th>&nbsp;</th>
                </tr>
                </thead>
                <tbody class="table-responsive">
                <?php foreach($contacts as $contact): ?>
                <tr class="table-striped">
                    <td><i class="fa fa-user text-danger"></i>&nbsp; <?= $contact->fulname ?> <br> <i class="fa fa-envelope-o text-primary">&nbsp; <?= $contact->email ?></i></td>
                    <td align="center"><i class="fa fa-phone text-primary"></i>&nbsp; <?= $contact->mobile ?></td>
                    <td align="center"><?php if($contact->idgroupe > 0): ?> <i class="fa fa-users text-info"></i>&nbsp; <?php endif; ?><?= ($contact->idgroupe > 0 ) ? $contact->groupe->nomgroupe: "" ?> </td>
                    <td align="center"><a href="update?id=<?= $contact->id ?>"><span class="glyphicon glyphicon-pencil text-warning"></span></a></td>
                    <td align="center"><a href="delete?id=<?= $contact->id ?>" data-confirm="<?= $contact->fulname ?>"><span class="glyphicon glyphicon-remove text-danger"></span></a></td>
                </tr>
                <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </div>
</div>
