<?php
if (!isset($contact)) {
    $contact = [];
}

?>
<div class="contain">
    <h4 class="text-warning">Modifier contact</h4>
    <div class="clearfix">&nbsp;</div>

    <div class="col-md-12 row notification">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
<?php endif; ?>
    </div>
    <div class="row">      
        <span class="clearfix">&nbsp;</span>
        <div class="col-md-12">
            <form action="update?id=<?= $contact->id ?>" method="post">
                <table class="table table-responsive">

                    <tr>
                        <td>
                            <span class="col-md-8">
                                <p ><span class="fa fa-user"></span><input type="text" class="form-control" placeholder="Nom et prenom" name="fulname" value=" <?= $contact->fulname ?>"></p>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>   
                            <span class="col-md-8"><p ><span class="fa fa-phone"></span><input type="text" class="form-control" name="mobile" value="<?= $contact->mobile ?>" placeholder="mobile"></p>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>  
                            <span class="col-md-8">
                                <p ><span class="fa fa-envelope"></span><input type="text" class="form-control" type="email" value="<?= $contact->email ?>" name="email" placeholder="email"></p>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <span class="col-md-8">
                                <p ><span class="fa fa-users"></span> 
                                    <select class="form-control select-goup" name="groupid">
                                        <option value="<?= ($contact->idgroupe > 0) ? $contact->idgroupe : '0' ?>"><?= ($contact->idgroupe > 0) ? $contact->groupe->nomgroupe : "---" ?></option>
                                        <?php
                                        foreach ($groupes as $value):
                                            if ($value->idgroupe != $contact->idgroupe):
                                                ?>
                                                <option value="<?= $value->idgroupe ?>"><?= $value->nomgroupe ?></option>
                                                <?php
                                            endif;
                                        endforeach;
                                        ?>
                                        <option value="0">---</option>
                                    </select></p>
                            </span>
                        </td>
                    </tr>
                    <tr>
                        <td>  
                            <span class="col-md-6">
                                <button type="submit" class="btn btn-primary btn-sm" >
                                    <i class="fa fa-check"></i> &nbsp;Modifier
                                </button> &nbsp;
                                 <a href="mesContacts" class="btn btn-default btn-sm"><i class="fa fa-backward text-warning"></i>&nbsp; Listes des contacts</a>
                            </span><br>
                        </td>
                    </tr>

                    </td>
                    </tr>                               
                </table> 
            </form>
        </div>        
    </div>
    <div class="clearfix">&nbsp;</div>

</div>

