<?php
if(!isset($profils)){
    $profils=[];
}
if(!isset($users)){
    $users=[];
}
$modifier= $this->session->get('mod');
$supprimer= $this->session->get('sup');
?>
<div class="contain">
   <div class="clearfix">&nbsp;</div>
   <h5 class="text-warning">Gestions des utilisateurs / <a href='newProfile'>Nouveau profil</a></h5>
    <div class="clearfix">&nbsp;</div>
    
    <div class="col-md-12 row">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
        <?php endif; ?>
    </div>

    <div class="row">
        <div class="col-md-12">
            <span  data-toggle="collapse" data-target="#demo1" style="cursor: alias;"><a href="#"><i class="fa fa-plus"></i> Ajouter un utilisateur</a></span>

        </div>
        <div id="demo1" class="collapse col-md-12">
            <span class="clearfix">&nbsp;</span>
            <form method="post" action="newUser">
            <div class="col-md-12">
                <table class="table table-responsive">
                    <tr class="table-striped">
                        <td>Nom:</td><td><input type='text' class="form-control" name='nom'></td>
                    </tr>

                    <tr>
                        <td>pseudo:</td><td><input type='text' class="form-control" name='pseudo'></td>
                    </tr>

                    <tr>
                        <td>email:</td><td><input type='text' class="form-control" name='mail'></td>
                    </tr>                   
                    <tr>
                        <td>profil:</td>
                        <td>
                            <select class="form-control" name='profil'>
                                <?php foreach ($profils as $profil): ?>
                                <option value="<?= $profil->idprofile ?>" ><?= $profil->nomprofile ?> </option> 
                               <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>                   
                    <tr>
                        <td>password:</td><td><input type='text' class="form-control" name='passworda'></td>
                    </tr>

                    <tr>
                        <td>confirm password:</td><td><input type='text' class="form-control" name='passwordb'></td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <span><label class="checkbox-inline"><input type="checkbox" name="actif" value="1"> Actif</label></span>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <button type='submit' name="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> &nbsp;Enregistrer</button>    &nbsp; 
                            <button type="reset" class="btn btn-default btn-sm">Annuler</button>
                        </td>
                    </tr>

                </table> 
            </div>

            </div>  
        </div>
    </div>
    <div class="clearfix">&nbsp;</div>
    <div class="row">
        <div class="col-md-12">
            <table class="table table-responsive table-striped">
                <tr class="table-striped">
                    <td> </td>
                    <td><b>N&deg;</b></td>
                    <td><b>Nom utilisateur</b></td>
                    <td align="center"><b>pseudo</b></td>
                    <td align="center"><b>mail</b></td>
                    <td align="center"><b>profil</b></td>
                    <td align="center"><b>Modifier</b></td> 
                    <td align="center"><b>supprimer</b></td>
                    
                </tr>
                
                <?php foreach ($users as $user): ?>
                <tr class="table-striped">
                    <td><i class="fa fa-user text-warning"></i></td>
                    <td><b><?= $user->iduser ?></b></td>
                    <td><?= $user->fulname ?></td>
                    <td align="center"><?= $user->pseudo ?></td>
                    <td align="center"><?= $user->email ?></td>
                    <td align="center"><?= $user->profile->nomprofile ?></td>
                    <td align="center"><a href="updateUser?id=<?= base64_encode($user->iduser) ?>"><span class="glyphicon glyphicon-pencil text-warning"></span></a></td>
                    <td align="center"><a href='deleteUser?id=<?= base64_encode($user->iduser) ?>' data-confirm="<?= $user->fulname ?>"><span class="glyphicon glyphicon-remove text-danger"></span></a></td>                    
                </tr>
                <?php endforeach; ?>
            </table>
        </div>
    </div>
</div>
