<?php
if (!isset($profils)) {
    $profils = [];
}
if (!isset($users)) {
    $users = [];
}
$modifier = $this->session->get('mod');
$supprimer = $this->session->get('sup');

?>
<div class="contain">
    <div class="clearfix">&nbsp;</div>
    <h5 class="text-warning">Gestions des utilisateurs / <a href='newUser'>Nouveau utilisateur</a></h5>
    <div class="clearfix">&nbsp;</div>

    <div class="col-md-12 row">
        <?php if (sizeof($this->flashSession->getMessages(NULL, false)) > 0): ?>
            <div><p><?php $this->flashSession->output() ?></p></div>
        <?php endif; ?>
    </div>

    <div class="row">


        <span class="clearfix">&nbsp;</span>
        <form method="post" action="updateUser?id=<?= $users->iduser ?>">
            <div class="col-md-12">
                <table class="table table-responsive">
                    <tr class="table-striped">
                        <td>Nom:</td><td><input type='text' class="form-control" name='nom' value="<?= $users->fulname ?>"></td>
                    </tr>

                    <tr>
                        <td>pseudo:</td><td><input type='text' class="form-control" name='pseudo' value="<?= $users->pseudo ?>"></td>
                    </tr>

                    <tr>
                        <td>email:</td><td><input type='text' class="form-control" name='mail' value="<?= $users->email ?>"></td>
                    </tr>                   
                    <tr>
                        <td>profil:</td>
                        <td>
                            <select class="form-control" name='profil'>
                                <option value="<?= $users->profile->idprofile ?>" selected="select"><?= $users->profile->nomprofile ?> </option>
                                <?php foreach ($profils as $profil): ?>
                                    <?php if ($users->idprofile != $profil->idprofile): ?>
                                        <option value="<?= $profil->idprofile ?>" ><?= $profil->nomprofile ?> </option>
                                    <?php endif; ?>
                                <?php endforeach; ?>
                            </select>
                        </td>
                    </tr>                   
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <span><input type="checkbox" name="actif" value="1" <?= ($users->actif == "1") ? "checked='checked'" : "" ?>> Actif</span>
                        </td>
                    </tr>
                    <tr>
                        <td>&nbsp;</td>
                        <td>
                            <button type='submit' name="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> &nbsp;Modifier</button>    &nbsp; 
                            <button type="reset" class="btn btn-default btn-sm">Annuler</button>
                            <a href="newUser" class="btn btn-default btn-sm"><i class="fa fa-backward text-warning"></i>&nbsp; Listes des utilisateurs</a>
                        </td>
                    </tr>

                </table> 
            </div>
        </form>
    </div>
</div>
<div class="clearfix">&nbsp;</div>
<div class="row">
    <div class="col-md-12">
        <h4 class="text-info">Changer le mot de passe</h4>
        <span>&nbsp;</span>
        <form method="post" action="pass?id= <?= $users->iduser ?>">
            <table class="table table-responsive">
                <tr class="table-striped">
                    <td>nouveau mot de passe:</td><td><input type='text' class="form-control" name='newpass'></td>
                </tr>
                <tr class="table-striped">
                    <td>confirm password:</td><td><input type='text' class="form-control" name='confirmpass'></td>
                </tr>
                <tr>
                    <td>ancien mot de password:</td><td><input type='text' class="form-control" name='lastpass'></td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <button type='submit' name="submit" class="btn btn-primary btn-sm"><i class="fa fa-check"></i> &nbsp;Changer</button>&nbsp; 
                        <button type="reset" class="btn btn-default btn-sm">Annuler</button>
                        <a href="newUser" class="btn btn-default btn-sm"><i class="fa fa-backward text-warning"></i>&nbsp; Listes des utilisateurs</a>
                    </td>
                </tr>
            </table>
        </form>
    </div>
</div>

</div>


